name: Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - release/1.0.1
  pull_request:
    branches:
      - release/1.0.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: hackathon-ready

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --yes
