name: Build and Publish Docker Image Into Digital Ocean Container Registry

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-push:
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      docker_image_prefix: registry.digitalocean.com/github-registry/molt-market
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
